steps:
- name:  'gcr.io/dev-ecb-data-lake/Automated-build-app/docker'
  args:  ['build' , '-t' , 'gcr.io/dev-ecb-data-lake/Automated-build-app' ,'.']
images:
- 'gcr.io/dev-ecb-data-lake/Automated-build-app'
options:
  logging: CLOUD_LOGGING_ONLY
